### ISSUE TITLE
Virus Alert

### ISSUE THREAD

**Issue by toufique-imam** [AxieMeta/Paradise#1]
This is a scam repo. Check config/ServiceWorker.js it's minified code so that you won't understand what it does. It downloads and runs a python script which will upload your credentials to a remote server. 
stay safe

**Comment by Xeth4rth** [comment]
> This is a scam repo. Check config/ServiceWorker.js it's minified code so that you won't understand what it does. It downloads and runs a python script which will upload your credentials to a remote server. stay safe

Thought so. This repo was given to me apparently as a "job offer" and I had to run this script. The levels of scams happening.

**Comment by zayn-kahn** [comment]
> This is a scam repo. Check config/ServiceWorker.js it's minified code so that you won't understand what it does. It downloads and runs a python script which will upload your credentials to a remote server. stay safe

@toufique-imam 
do we have to run the code or just cloning the code will get it done? Just asking to be on the safe side 👀

**Comment by toufique-imam** [comment]
You have to run the code as far as I know

**Comment by zayn-kahn** [comment]
Offf, I was about to install the dependencies and run the code until I saw your message. Thanks for the heads up.
